## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

dataframe = pd.DataFrame(data)
# alternatively, this also works:
# dataframe = pd.DataFrame(data, columns=["job", "family_size", "num_cars"], index=[data['name']])

print(dataframe)
# Select people that are psychologist or teacher and their number of cars is greater than their family size.
dataframe[((dataframe['job'] == 'psychologist') | (dataframe["job"] == "teacher")) & (dataframe["num_cars"] > dataframe["family_size"])]

# Select people who have at most 2 family members and at least 1 car.
dataframe[(dataframe['family_size'] <= 2) & (dataframe['num_cars'] >= 1)]

# create initial variables
dummy = dataframe.iloc[0]['job']
# create a list to hold known values
known = [dummy]
# loop through and append known when encountering a new variable
for i in range(len(dataframe['job'])):
  if dataframe.iloc[i]['job'] not in known:
    known.append(dataframe.iloc[i]['job'])

print("\nNumer of unique jobs: " + str(len(known)))


     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

Numer of unique jobs: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# create lists to store the weights of each fruit
apples = []
bananas = []
carrots = []

# create a dictionary of the fruits/weights
dictionary = {'fruits': fruit, 'weights': weights}

# create a dataframe of the fruits and their respective weights
dataframe = pd.DataFrame(dictionary)
print(dataframe)

# traverse the dataframe and load the fruit weights into their respective lists
for i in range(len(dataframe['weights'])):
  if dataframe.iloc[i]['fruits'] == 'apple':
    apples.append(dataframe.iloc[i]['weights'])
  elif dataframe.iloc[i]['fruits'] == 'banana':
    bananas.append(dataframe.iloc[i]['weights'])
  elif dataframe.iloc[i]['fruits'] == 'carrot':
    carrots.append(dataframe.iloc[i]['weights'])

# the mean weights of each fruit are intuitively just the sum of the list
# of their weights divided by the length of that list
print('\napple mean weight: ' + str(round((sum(apples)/len(apples)), 2)))
print('banana mean weight: ' + str(round((sum(bananas)/len(bananas)), 2)))
print('carrot mean weight: ' + str(round((sum(carrots)/len(carrots)), 2)))


   fruits  weights
0  carrot      1.0
1  carrot      2.0
2   apple      3.0
3   apple      4.0
4   apple      5.0
5   apple      6.0
6  banana      7.0
7   apple      8.0
8   apple      9.0
9   apple     10.0

apple mean weight: 6.43
banana mean weight: 7.0
carrot mean weight: 1.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

# create a dictionary to hold indices
dictionary = {}
# traverse course_name to append dictionary
for i in range(len(course_name)):
  dictionary[course_name[i]] = i 

# create the sorted array
sorted = np.sort(course_name)
# create the sorted indices array and trave
sorted_indices = []
# traverse sorted to (load into) sorted_indices using the dictionary
for i in range(len(sorted)):
  sorted_indices.append(dictionary[sorted[i]])

print("The sorted elements are: ")
print(sorted)
print("Their indices are: ")
print(sorted_indices)
print('')

# create boolean list
boolean = []
for i in range(len(course_name)):
  boolean.append(False)
# create dummy string
string = ''
# traverse through the array to check if each element starts with a p
for i in range(len(course_name)):
  string = course_name[i].lower()
  if string[0][0] == 'p':
    boolean[i] = True

#print("boolean array to judge whether each element of course_name starts with a p:")
#print(boolean)

# create dictionary to display it in a more succinct way
dict2 = {}
for i in range(len(course_name)):
  if boolean[i] == True:
    dict2[i] = 'yes'
  else:
    dict2[i] = 'no'

print("Does the element at each index start with a p? ")
print(dict2)

The sorted elements are: 
['JS' 'PHP' 'Python' 'examples' 'html']
Their indices are: 
[1, 3, 0, 2, 4]

Does the element at each index start with a p? 
{0: 'yes', 1: 'no', 2: 'no', 3: 'yes', 4: 'no'}


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# copy array into orginal
original = student_id

# use slicing to reverse student_id
reversed = student_id[::-1]

print("orignal array: ")
print(original)
print("reversed array: ")
print(reversed)

# initialize max
max = student_id[0]
index = 0
# traverse the array to find a new max, then replace max if found
for i in range(len(student_id)):
  if student_id[i] > max:
    max = student_id[i]
    index = i
# delete the max from the array 
student_id = np.delete(student_id, index)

# repeat the process to find the second largest
max2 = student_id[0]
index = 0
# traverse the array to find a new max, then replace max if found
for i in range(len(student_id)):
  if student_id[i] > max2:
    max2 = student_id[i]
    index = i
# delete the max from the array 
student_id = np.delete(student_id, index)

# repeat it again
max3 = student_id[0]
index = 0
# traverse the array to find a new max, then replace max if found
for i in range(len(student_id)):
  if student_id[i] > max3:
    max3 = student_id[i]
    index = i

print("\nThe three largests values are (in order from highest to lowest): " + str(max) + ', ' + str(max2) + ', ' + str(max3))


orignal array: 
[1023 5202 6230 1671 1682 5241 4532]
reversed array: 
[4532 5241 1682 1671 6230 5202 1023]

The three largests values are (in order from highest to lowest): 6230, 5241, 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np         
# initialize list to hold multiples
multiples_3or5 = []

# create array of 100 nums
nums = np.arange(1, 100)

# travers nums to check if each element is a multiple of 3 or 5
for i in range(len(nums)):
  # modulo operations will allow us to see if each element fits the bill
  if (nums[i] % 3 == 0) or (nums[i] % 5 == 0):
    multiples_3or5.append(nums[i])

print("Sum of all multiples of 3 or 5 below 100 = " + str(sum(multiples_3or5)))



# Hint: you can use arange to start off

Sum of all multiples of 3 or 5 below 100 = 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

# swap the columns using slicing
swaped = np.copy(arr)
# : is the rows arg since we want all the rows, but 
# 0 and 1 are the col args since we want to switch them
swaped[:, [1,2]] = swaped[:, [2,1]]
print('Col 1 and 2 swaped: ')
print(swaped)

# swap the rows using slicing as well
rows_swap = np.copy(arr)
# same intution as above, this time varying the rows arg
rows_swap[[0,1], :] = rows_swap[[1,0], :]
print('Row 0 and 1 swaped: ')
print(rows_swap)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Col 1 and 2 swaped: 
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Row 0 and 1 swaped: 
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
